---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 25.02.2026 ###

## Horizon service
horizon_git_repo: "{{ openstack_opendev_base_url }}/openstack/horizon"
horizon_git_install_branch: 665783683b1844f3342e0e628fab85a95363b06f
horizon_git_track_branch: master

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/adjutant-ui"
adjutant_dashboard_git_install_branch: 6d3d12d267d1405e0bf64f43cc3d757b72eb68a0
adjutant_dashboard_git_track_branch: master

## Barbican dashboard plugin
barbican_dashboard_git_repo: "{{ openstack_opendev_base_url }}//openstack/barbican-ui"
barbican_dashboard_git_install_branch: f962e455b529580c2bb0e924a6fd39185a77ec16
barbican_dashboard_git_track_branch: master

## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-dashboard"
cloudkitty_dashboard_git_install_branch: f4067c0ba5cc910b6c99984c5f1e539e8d75583f
cloudkitty_dashboard_git_track_branch: master

## Horizon Designate dashboard plugin
designate_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-dashboard"
designate_dashboard_git_install_branch: f235f5e601a909c49d040cd1f9e512661e56d8fd
designate_dashboard_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-dashboard"
heat_dashboard_git_install_branch: d47d1b136f3cc9619a06a00c6867abb8701d878e
heat_dashboard_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: "{{ openstack_opendev_base_url}}/openstack/ironic-ui"
ironic_dashboard_git_install_branch: 7906524daa0b3fb6d8c3caa060fd5352a3963c55
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-ui"
magnum_dashboard_git_install_branch: ae73f2530541fea448882f9009a1acff6d2c43ab
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-dashboard"
masakari_dashboard_git_install_branch: d68e4793e18d472ee2d6bfcda745bfc3b6ac891f
masakari_dashboard_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-dashboard"
trove_dashboard_git_install_branch: cbc6e7ae5b4188b5da39df368390ab94e723e980
trove_dashboard_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-dashboard"
octavia_dashboard_git_install_branch: 674b34f2bec18c5ef2b18bdbeb7b0e1c43428328
octavia_dashboard_git_track_branch: master

## Horizon Neutron VPNaaS dashboard plugin
neutron_vpnaas_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-vpnaas-dashboard"
neutron_vpnaas_dashboard_git_install_branch: 5c5f300b52fc9add1124232330184b274b8eff8a
neutron_vpnaas_dashboard_git_track_branch: master

## Horizon Neutron FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-fwaas-dashboard"
neutron_fwaas_dashboard_git_install_branch: e730567424e86a8dc8ed759631f46af8c3b05f36
neutron_fwaas_dashboard_git_track_branch: master
