---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 07.10.2026 ###

## Horizon service
horizon_git_repo: "{{ openstack_opendev_base_url }}/openstack/horizon"
horizon_git_install_branch: a1aa93d9ac6a329db2fa480ce2232bf8873b8751
horizon_git_track_branch: stable/2026.1

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/adjutant-ui"
adjutant_dashboard_git_install_branch: 9e78882f50d5787566b02b174564502f38cdebc7
adjutant_dashboard_git_track_branch: stable/2026.1

## Barbican dashboard plugin
barbican_dashboard_git_repo: "{{ openstack_opendev_base_url }}//openstack/barbican-ui"
barbican_dashboard_git_install_branch: 3285e42b0297802bf74270fa755ee6be514f8dc7
barbican_dashboard_git_track_branch: master

## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-dashboard"
cloudkitty_dashboard_git_install_branch: 31573116b52a9cf22330b30776cc0add2dd0d12a
cloudkitty_dashboard_git_track_branch: stable/2026.1

## Horizon Designate dashboard plugin
designate_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-dashboard"
designate_dashboard_git_install_branch: 31b47ba01ca0d319e5e3064fa62d5c68b088a7b0
designate_dashboard_git_track_branch: stable/2026.1

## Horizon Freezer dashboard plugin
freezer_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/freezer-web-ui"
freezer_dashboard_git_install_branch: c1568c607a05167142a5e6d37920aa37029f5c3e
freezer_dashboard_git_track_branch: stable/2026.1

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-dashboard"
heat_dashboard_git_install_branch: 59006fbfc7e2dc85ea1a2082d4bdb5733e6a5bf1
heat_dashboard_git_track_branch: stable/2026.1

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: "{{ openstack_opendev_base_url}}/openstack/ironic-ui"
ironic_dashboard_git_install_branch: 16e768e11f580e4a993a294e4a27eb1d8ed1a0bd
ironic_dashboard_git_track_branch: stable/2026.1

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-ui"
magnum_dashboard_git_install_branch: 6f663d6fa3f0b5ea7bfc6dd512517cb737140fb6
magnum_dashboard_git_track_branch: stable/2026.1

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-dashboard"
masakari_dashboard_git_install_branch: d18017941eb93288802f7d9c6d9eecd16424ab5f
masakari_dashboard_git_track_branch: stable/2026.1

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-dashboard"
trove_dashboard_git_install_branch: 3e3975c3b3427bb384fa311da1e6684c740fd97f
trove_dashboard_git_track_branch: stable/2026.1

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-dashboard"
octavia_dashboard_git_install_branch: 5f3f1f74249f2a67ad92c59fae2b2f501a458673
octavia_dashboard_git_track_branch: stable/2026.1

## Horizon Neutron VPNaaS dashboard plugin
neutron_vpnaas_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-vpnaas-dashboard"
neutron_vpnaas_dashboard_git_install_branch: c1df4eed3a8bad77a0b05e0e3f0fef87d080c661
neutron_vpnaas_dashboard_git_track_branch: stable/2026.1

## Horizon Neutron FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-fwaas-dashboard"
neutron_fwaas_dashboard_git_install_branch: af86dbf46e0d644f82386132a4d32e82095c76d9
neutron_fwaas_dashboard_git_track_branch: stable/2026.1
