---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 28.09.2026 ###

## Horizon service
horizon_git_repo: "{{ openstack_opendev_base_url }}/openstack/horizon"
horizon_git_install_branch: 667a08d4cbb0c56a7a462bedbd359a35526c726e
horizon_git_track_branch: stable/2026.2

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/adjutant-ui"
adjutant_dashboard_git_install_branch: 0664159a256f439f621b295532aa2ee00b83b61d
adjutant_dashboard_git_track_branch: stable/2026.2

## Barbican dashboard plugin
barbican_dashboard_git_repo: "{{ openstack_opendev_base_url }}//openstack/barbican-ui"
barbican_dashboard_git_install_branch: 3285e42b0297802bf74270fa755ee6be514f8dc7
barbican_dashboard_git_track_branch: None

## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-dashboard"
cloudkitty_dashboard_git_install_branch: ff39073c83be87682018563a34775669e7030626
cloudkitty_dashboard_git_track_branch: stable/2026.2

## Horizon Designate dashboard plugin
designate_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-dashboard"
designate_dashboard_git_install_branch: f4c230b2f035be1b96f6dc69d64327a798efd508
designate_dashboard_git_track_branch: stable/2026.2

## Horizon Freezer dashboard plugin
freezer_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/freezer-web-ui"
freezer_dashboard_git_install_branch: 9079d4d2b0de5ca735a82cbecd886fbed6b9a4fa
freezer_dashboard_git_track_branch: stable/2026.2

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-dashboard"
heat_dashboard_git_install_branch: a6e9b7186f870f95305d2f9f7881cd132787343e
heat_dashboard_git_track_branch: stable/2026.2

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/ironic-ui"
ironic_dashboard_git_install_branch: 5ea0995afe5fad346a8cca1b5911593d64df8353
ironic_dashboard_git_track_branch: stable/2026.2

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-ui"
magnum_dashboard_git_install_branch: 226ccc54e57aa1c6a53bd8d60c23e047b7c35cdf
magnum_dashboard_git_track_branch: stable/2026.2

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-dashboard"
masakari_dashboard_git_install_branch: 4d8a70fa52a63163bfe87f2d9355aeaa8903ce77
masakari_dashboard_git_track_branch: stable/2026.2

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-dashboard"
trove_dashboard_git_install_branch: 996a015412529cbfbdff5d9bc585146bc272c1a8
trove_dashboard_git_track_branch: stable/2026.2

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-dashboard"
octavia_dashboard_git_install_branch: 04a51213afb6658b55d0fdf1bad1ae9634b44a9e
octavia_dashboard_git_track_branch: stable/2026.2

## Horizon Neutron VPNaaS dashboard plugin
neutron_vpnaas_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-vpnaas-dashboard"
neutron_vpnaas_dashboard_git_install_branch: c8aa0314eaca76d1a3b9a3eab65c4aefd2ec83f0
neutron_vpnaas_dashboard_git_track_branch: stable/2026.2

## Horizon Neutron FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-fwaas-dashboard"
neutron_fwaas_dashboard_git_install_branch: 6b5eee6b1ff895b77197830a82c23bd74e4aeb6f
neutron_fwaas_dashboard_git_track_branch: stable/2026.2

## Horizon Zun dashboard plugin
zun_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/zun-ui"
zun_dashboard_git_install_branch: a9031968e1ab02565cf3f2e0a6c76d247f480eaf
zun_dashboard_git_track_branch: stable/2026.2
