---
features:
  - |
    Added new configuration option ``horizon_swift_panel_full_listing``
    that defaults to ``false``. To prevent Horizon from doing
    full listing of containers and objects in the Swift panel that can
    cause high resource consumption in Horizon.
