---
component_skel:
  ceilometer_agent_compute:
    belongs_to:
     - ceilometer_all
  ceilometer_agent_central:
    belongs_to:
      - ceilometer_all
  ceilometer_agent_notification:
    belongs_to:
     - ceilometer_all

container_skel:
  ceilometer_central_container:
    belongs_to:
      - metering_infra_containers
    contains:
      - ceilometer_agent_central
      - ceilometer_agent_notification
  ceilometer_compute_container:
    belongs_to:
      - metering_compute_containers
    contains:
      - ceilometer_agent_compute
    properties:
      is_metal: true

physical_skel:
  metering_compute_containers:
    belongs_to:
      - all_containers
  metering_compute_hosts:
    belongs_to:
      - hosts
  metering_infra_containers:
    belongs_to:
      - all_containers
  metering_infra_hosts:
    belongs_to:
      - hosts
