---
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

component_skel:
  ceph_mon:
    belongs_to:
      - ceph_all
  ceph_osd:
    belongs_to:
      - ceph_all
  ceph_rgw:
    belongs_to:
      - ceph_all
  ceph_mds:
    belongs_to:
      - ceph_all
  ceph_nfs:
    belongs_to:
      - ceph_all

container_skel:
  ceph_mon_container:
    belongs_to:
      - ceph_mon_containers
    contains:
      - ceph_mon
  ceph_osd_container:
    belongs_to:
      - ceph_osd_containers
    contains:
      - ceph_osd
    properties:
      is_metal: true
  ceph_rgw_container:
    belongs_to:
      - ceph_rgw_containers
    contains:
      - ceph_rgw
  ceph_mds_container:
    belongs_to:
      - ceph_mds_containers
    contains:
      - ceph_mds
  ceph_nfs_container:
    belongs_to:
      - ceph_nfs_containers
    contains:
      - ceph_nfs

physical_skel:
  ceph_mon_containers:
    belongs_to:
      - all_containers
  ceph_mon_hosts:
    belongs_to:
      - hosts
  ceph_osd_containers:
    belongs_to:
      - all_containers
  ceph_osd_hosts:
    belongs_to:
      - hosts
  ceph_rgw_containers:
    belongs_to:
      - all_containers
  ceph_rgw_hosts:
    belongs_to:
      - hosts
  ceph_mds_containers:
    belongs_to:
      - all_containers
  ceph_mds_hosts:
    belongs_to:
      - hosts
  ceph_nfs_containers:
    belongs_to:
      - all_containers
  ceph_nfs_hosts:
    belongs_to:
      - hosts
