---
# Copyright 2018, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 19.06.2026 ###

tempest_git_repo: "{{ openstack_opendev_base_url }}/openstack/tempest"
tempest_git_install_branch: 910c766019aa24043d30b6dad275e0935c9f2ed2
tempest_git_track_branch: master

tempest_plugin_barbican_git_repo: "{{ openstack_opendev_base_url }}/openstack/barbican-tempest-plugin"
tempest_plugin_barbican_git_install_branch: 159c8cbd8d47e2b194119c77fa38f19016cf42d0
tempest_plugin_barbican_git_track_branch: master

tempest_plugin_blazar_git_repo: "{{ openstack_opendev_base_url }}/openstack/blazar-tempest-plugin"
tempest_plugin_blazar_git_install_branch: 0249df2b69de241bfbbf621c35e4c4dee32c153c
tempest_plugin_blazar_git_track_branch: master

tempest_plugin_cinder_git_repo: "{{ openstack_opendev_base_url }}/openstack/cinder-tempest-plugin"
tempest_plugin_cinder_git_install_branch: 29bb6f77210404a4b70e4143cd9c3c9912534af7
tempest_plugin_cinder_git_track_branch: master

tempest_plugin_cloudkitty_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-tempest-plugin"
tempest_plugin_cloudkitty_git_install_branch: fc8dc2a0011b13729df196f0203d0399627a0d01
tempest_plugin_cloudkitty_git_track_branch: master

tempest_plugin_designate_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-tempest-plugin"
tempest_plugin_designate_git_install_branch: 4df30ac8dd97b5288a40a3c2af31752b82ed28bd
tempest_plugin_designate_git_track_branch: master

tempest_plugin_freezer_git_repo: "{{ openstack_opendev_base_url }}/openstack/freezer-tempest-plugin"
tempest_plugin_freezer_git_install_branch: 22285fc6d88e8cf3acee85b822dbdb52c75fbbcd
tempest_plugin_freezer_git_track_branch: master

tempest_plugin_glance_git_repo: "{{ openstack_opendev_base_url }}/openstack/glance-tempest-plugin"
tempest_plugin_glance_git_install_branch: 88c9129924a2a94088d77f403bad2a8cde78fd57
tempest_plugin_glance_git_track_branch: master

tempest_plugin_heat_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-tempest-plugin"
tempest_plugin_heat_git_install_branch: 768254a8ecce30dd006afb59f0893bd78e4ea23a
tempest_plugin_heat_git_track_branch: master

tempest_plugin_ironic_git_repo: "{{ openstack_opendev_base_url }}/openstack/ironic-tempest-plugin"
tempest_plugin_ironic_git_install_branch: 8cb7c55ac59209ef9daa7ff4c74070960acb01eb
tempest_plugin_ironic_git_track_branch: master

tempest_plugin_keystone_git_repo: "{{ openstack_opendev_base_url }}/openstack/keystone-tempest-plugin"
tempest_plugin_keystone_git_install_branch: dc6299e8f1c28eb81fced84a6dc08792090327e6
tempest_plugin_keystone_git_track_branch: master

tempest_plugin_magnum_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-tempest-plugin"
tempest_plugin_magnum_git_install_branch: 961028527eb737cf5a99f325d521fbbfbee90306
tempest_plugin_magnum_git_track_branch: master

tempest_plugin_manila_git_repo: "{{ openstack_opendev_base_url }}/openstack/manila-tempest-plugin"
tempest_plugin_manila_git_install_branch: fc809ff749625f28a276d2f5ab7c1cb12f992569
tempest_plugin_manila_git_track_branch: master

tempest_plugin_neutron_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-tempest-plugin"
tempest_plugin_neutron_git_install_branch: f80cd304cf6ce6dc33b3e1b230cfe9fb9eaa280e
tempest_plugin_neutron_git_track_branch: master

tempest_plugin_octavia_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-tempest-plugin"
tempest_plugin_octavia_git_install_branch: bb4776fabba145a03ea0b0df379dcd63d1a26a90
tempest_plugin_octavia_git_track_branch: master

tempest_plugin_telemetry_git_repo: "{{ openstack_opendev_base_url }}/openstack/telemetry-tempest-plugin"
tempest_plugin_telemetry_git_install_branch: 4a7e99a9c93fb797d853b6438bc795073eef5bb3
tempest_plugin_telemetry_git_track_branch: master

tempest_plugin_trove_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-tempest-plugin"
tempest_plugin_trove_git_install_branch: 01672d24d26b9b6ec2c750c1ff6c1b4092af769a
tempest_plugin_trove_git_track_branch: master

tempest_plugin_zun_git_repo: "{{ openstack_opendev_base_url }}/openstack/zun-tempest-plugin"
tempest_plugin_zun_git_install_branch: d8595f07c74f1314f15beb8e42ca68d2b552a036
tempest_plugin_zun_git_track_branch: master

rally_openstack_git_repo: "{{ openstack_opendev_base_url }}/openstack/rally-openstack"
rally_openstack_git_install_branch: 97e84637b02bf991f30091d8a35947b3aaf516a1
rally_openstack_git_track_branch: master
