---
# Copyright 2018, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 26.03.2026 ###

tempest_git_repo: "{{ openstack_opendev_base_url }}/openstack/tempest"
tempest_git_install_branch: a45d14bead8545840c644b869ba80bd60974a1b9
tempest_git_track_branch: None

tempest_plugin_barbican_git_repo: "{{ openstack_opendev_base_url }}/openstack/barbican-tempest-plugin"
tempest_plugin_barbican_git_install_branch: 82a83c0c759e0cc168022bc03ca3461fe3417358
tempest_plugin_barbican_git_track_branch: None

tempest_plugin_blazar_git_repo: "{{ openstack_opendev_base_url }}/openstack/blazar-tempest-plugin"
tempest_plugin_blazar_git_install_branch: fee48c7ba8316fae17d1dd7e2cfba5896edece64
tempest_plugin_blazar_git_track_branch: None

tempest_plugin_cinder_git_repo: "{{ openstack_opendev_base_url }}/openstack/cinder-tempest-plugin"
tempest_plugin_cinder_git_install_branch: b790e27b567735e285319e46fdf9150561c4782d
tempest_plugin_cinder_git_track_branch: None

tempest_plugin_cloudkitty_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-tempest-plugin"
tempest_plugin_cloudkitty_git_install_branch: ef9563733be423e06b95e7a9e2ad2c8b5e48059d
tempest_plugin_cloudkitty_git_track_branch: None

tempest_plugin_designate_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-tempest-plugin"
tempest_plugin_designate_git_install_branch: 38ab7320533b422ae1be0daaaa875d82eb08688f
tempest_plugin_designate_git_track_branch: None

tempest_plugin_freezer_git_repo: "{{ openstack_opendev_base_url }}/openstack/freezer-tempest-plugin"
tempest_plugin_freezer_git_install_branch: 90b68c226ba819294005e45b57a94cec9ac01f12
tempest_plugin_freezer_git_track_branch: None

tempest_plugin_glance_git_repo: "{{ openstack_opendev_base_url }}/openstack/glance-tempest-plugin"
tempest_plugin_glance_git_install_branch: 54889708741080bd7d7119730a68873ca51d686c
tempest_plugin_glance_git_track_branch: None

tempest_plugin_heat_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-tempest-plugin"
tempest_plugin_heat_git_install_branch: 7495223039ca5874cd511238b2de72e3471856d4
tempest_plugin_heat_git_track_branch: None

tempest_plugin_ironic_git_repo: "{{ openstack_opendev_base_url }}/openstack/ironic-tempest-plugin"
tempest_plugin_ironic_git_install_branch: e596e40f787557ff2908da797b26f14361662ae9
tempest_plugin_ironic_git_track_branch: None

tempest_plugin_keystone_git_repo: "{{ openstack_opendev_base_url }}/openstack/keystone-tempest-plugin"
tempest_plugin_keystone_git_install_branch: 4d96ff9583eb784b1d0ad2c9816d884bc8dd8d18
tempest_plugin_keystone_git_track_branch: None

tempest_plugin_magnum_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-tempest-plugin"
tempest_plugin_magnum_git_install_branch: cb9573136a418c18e45774bb67785c0ecffd156d
tempest_plugin_magnum_git_track_branch: None

tempest_plugin_manila_git_repo: "{{ openstack_opendev_base_url }}/openstack/manila-tempest-plugin"
tempest_plugin_manila_git_install_branch: 12145b00c527273c2dd30f453e9cb70aab57f6b8
tempest_plugin_manila_git_track_branch: None

tempest_plugin_neutron_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-tempest-plugin"
tempest_plugin_neutron_git_install_branch: 18bb3512772cb33bb8fc82f53ab49fb6309a58e4
tempest_plugin_neutron_git_track_branch: None

tempest_plugin_octavia_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-tempest-plugin"
tempest_plugin_octavia_git_install_branch: 65d580b5b084d392da682f6e2512b1f3ea93297b
tempest_plugin_octavia_git_track_branch: None

tempest_plugin_telemetry_git_repo: "{{ openstack_opendev_base_url }}/openstack/telemetry-tempest-plugin"
tempest_plugin_telemetry_git_install_branch: e168216919e49133575dc2327f20e2c89b23b683
tempest_plugin_telemetry_git_track_branch: None

tempest_plugin_trove_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-tempest-plugin"
tempest_plugin_trove_git_install_branch: 01672d24d26b9b6ec2c750c1ff6c1b4092af769a
tempest_plugin_trove_git_track_branch: None

tempest_plugin_zun_git_repo: "{{ openstack_opendev_base_url }}/openstack/zun-tempest-plugin"
tempest_plugin_zun_git_install_branch: d8595f07c74f1314f15beb8e42ca68d2b552a036
tempest_plugin_zun_git_track_branch: None

rally_openstack_git_repo: "{{ openstack_opendev_base_url }}/openstack/rally-openstack"
rally_openstack_git_install_branch: 4ceffd8c39414c1a8ede884c62bf06080aede5cd
rally_openstack_git_track_branch: None
