---
# Copyright 2018, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 28.09.2026 ###

tempest_git_repo: "{{ openstack_opendev_base_url }}/openstack/tempest"
tempest_git_install_branch: 5692e968f9e26bd86559efa765f6e5f47f6bf72d
tempest_git_track_branch: None

tempest_plugin_barbican_git_repo: "{{ openstack_opendev_base_url }}/openstack/barbican-tempest-plugin"
tempest_plugin_barbican_git_install_branch: f370cf0ee9e72ada0f48bf80360b7de851444b8e
tempest_plugin_barbican_git_track_branch: None

tempest_plugin_blazar_git_repo: "{{ openstack_opendev_base_url }}/openstack/blazar-tempest-plugin"
tempest_plugin_blazar_git_install_branch: 8b486e9745e5769517d0c5fcc710dc09267af863
tempest_plugin_blazar_git_track_branch: None

tempest_plugin_cinder_git_repo: "{{ openstack_opendev_base_url }}/openstack/cinder-tempest-plugin"
tempest_plugin_cinder_git_install_branch: d4894b4df9916d5f7b1968a4e3093f40af4eed44
tempest_plugin_cinder_git_track_branch: None

tempest_plugin_cloudkitty_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-tempest-plugin"
tempest_plugin_cloudkitty_git_install_branch: fc8dc2a0011b13729df196f0203d0399627a0d01
tempest_plugin_cloudkitty_git_track_branch: None

tempest_plugin_designate_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-tempest-plugin"
tempest_plugin_designate_git_install_branch: 4c69b6f219de7d6ad3b07be1f572edba64aab0c7
tempest_plugin_designate_git_track_branch: None

tempest_plugin_freezer_git_repo: "{{ openstack_opendev_base_url }}/openstack/freezer-tempest-plugin"
tempest_plugin_freezer_git_install_branch: 0ac02c2a6b68f818f61bf0664f346a081b5c3add
tempest_plugin_freezer_git_track_branch: None

tempest_plugin_glance_git_repo: "{{ openstack_opendev_base_url }}/openstack/glance-tempest-plugin"
tempest_plugin_glance_git_install_branch: 841dc52c5ea48f744bb4d0bd9d92bc94712f98b3
tempest_plugin_glance_git_track_branch: None

tempest_plugin_heat_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-tempest-plugin"
tempest_plugin_heat_git_install_branch: a59ce342a9443aac1276ce0789e031d383f879b5
tempest_plugin_heat_git_track_branch: None

tempest_plugin_ironic_git_repo: "{{ openstack_opendev_base_url }}/openstack/ironic-tempest-plugin"
tempest_plugin_ironic_git_install_branch: 88dbe63b3c77c7c8c7fcfe97b52a5409def4f7ef
tempest_plugin_ironic_git_track_branch: None

tempest_plugin_keystone_git_repo: "{{ openstack_opendev_base_url }}/openstack/keystone-tempest-plugin"
tempest_plugin_keystone_git_install_branch: 0266d55ff82ebd7b3a4c91f726e67a2bf4868afb
tempest_plugin_keystone_git_track_branch: None

tempest_plugin_magnum_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-tempest-plugin"
tempest_plugin_magnum_git_install_branch: 0e366e745bde11716a14ec90a56dbe826a454ac5
tempest_plugin_magnum_git_track_branch: None

tempest_plugin_manila_git_repo: "{{ openstack_opendev_base_url }}/openstack/manila-tempest-plugin"
tempest_plugin_manila_git_install_branch: 883d988ba173bd646a46f1e3aab3a37aba12a1ec
tempest_plugin_manila_git_track_branch: None

tempest_plugin_neutron_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-tempest-plugin"
tempest_plugin_neutron_git_install_branch: 570da83228d0deaa09c3cff203f0e00ed874cbec
tempest_plugin_neutron_git_track_branch: None

tempest_plugin_octavia_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-tempest-plugin"
tempest_plugin_octavia_git_install_branch: c63f8a5ebe7e0c2d7840120b6029f4260064fe9c
tempest_plugin_octavia_git_track_branch: None

tempest_plugin_telemetry_git_repo: "{{ openstack_opendev_base_url }}/openstack/telemetry-tempest-plugin"
tempest_plugin_telemetry_git_install_branch: 0037426bafafd4b6cf0926f17ae601620643b887
tempest_plugin_telemetry_git_track_branch: None

tempest_plugin_trove_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-tempest-plugin"
tempest_plugin_trove_git_install_branch: 362f7b1505d8e6a062cd66e07fd0aa373da76ee8
tempest_plugin_trove_git_track_branch: None

tempest_plugin_zun_git_repo: "{{ openstack_opendev_base_url }}/openstack/zun-tempest-plugin"
tempest_plugin_zun_git_install_branch: e81a36a61211c7d7a239bb12f4c4dfaf32a9a474
tempest_plugin_zun_git_track_branch: None

rally_openstack_git_repo: "{{ openstack_opendev_base_url }}/openstack/rally-openstack"
rally_openstack_git_install_branch: d7a145cc3db3b1a20db0601c3f2eddc15390f962
rally_openstack_git_track_branch: None
