---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 26.03.2026 ###

## Masakari service
masakari_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari"
masakari_git_install_branch: aee50d07d1319354f07dfc5ecfd58d2288da6491
masakari_git_track_branch: stable/2026.1

## Masakari monitors services
masakari_monitors_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-monitors"
masakari_monitors_git_install_branch: ab20062cec3a54cda486c953df2bc92cfb13cfd3
masakari_monitors_git_track_branch: stable/2026.1
