---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 19.06.2026 ###

## Masakari service
masakari_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari"
masakari_git_install_branch: 950cbd92e5e4e06b2be3b29ba020f5af22e9341d
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-monitors"
masakari_monitors_git_install_branch: d76a0d843f5d368b5d3b894bec29c6c17d23a82a
masakari_monitors_git_track_branch: master
