---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 19.08.2026 ###

## Neutron service
neutron_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron"
neutron_git_install_branch: 9aaa6faac469a6161e1dc771b3fc2791889cbba2
neutron_git_track_branch: master

neutron_vpnaas_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-vpnaas"
neutron_vpnaas_git_install_branch: 8f7a37e213cd5212f516a87ff054b7325d50f2fd
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-fwaas"
neutron_fwaas_git_install_branch: a1e5ac74468c67f8e757a7afbc2d5e369e1a49ce
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-dynamic-routing"
neutron_dynamic_routing_git_install_branch: 19962074d036514154d6c3c6cd307b3faea378d6
neutron_dynamic_routing_git_track_branch: master

networking_bgpvpn_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-bgpvpn"
networking_bgpvpn_git_install_branch: 13c86c38b9ca7efecea7db64570644d63045f5cc
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-sfc"
networking_sfc_git_install_branch: 81757fd69f3aa652180590590dcb47893540770f
networking_sfc_git_track_branch: master

networking_generic_switch_git_repo: "{{ openstack_opendev_base_url}}/openstack/networking-generic-switch"
networking_generic_switch_git_install_branch: 42c59790d62a3ece7c9674a678a20e3ddf80b5b1
networking_generic_switch_git_track_branch: master

networking_nsx_git_repo: "{{ openstack_opendev_base_url }}/x/vmware-nsx"
networking_nsx_git_install_branch: 715cb5fc1174b9226f043e49ffd389add44f070a
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: "{{ openstack_opendev_base_url }}/x/vmware-nsxlib"
networking_nsxlib_git_install_branch: 315a42f28e8a9e0e75773dbd8263bc11a72288df
networking_nsxlib_git_track_branch: master

networking_baremetal_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-baremetal"
networking_baremetal_git_install_branch: 7b532a8906622c4e7b8cc9b6209cbb1067bdc9b8
networking_baremetal_git_track_branch: master

networking_ovn_bgp_git_repo: "{{ openstack_opendev_base_url }}/openstack/ovn-bgp-agent"
networking_ovn_bgp_git_install_branch: 6c1a7ab909e01bbef7faa6b4ffc11f20c3573ac2
networking_ovn_bgp_git_track_branch: master
