---
# Copyright 2023, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 28.09.2026 ###

## Neutron service
neutron_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron"
neutron_git_install_branch: 9f015d5f5300d2b6b231993eec2bf1e450076ba3
neutron_git_track_branch: stable/2026.2

neutron_vpnaas_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-vpnaas"
neutron_vpnaas_git_install_branch: cd333cf6d6d5c544684c52df9e5ecd0e6679f00c
neutron_vpnaas_git_track_branch: stable/2026.2

neutron_fwaas_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-fwaas"
neutron_fwaas_git_install_branch: 5303a4deed1ec636453c005f2b1bb1ff8aa62395
neutron_fwaas_git_track_branch: stable/2026.2

neutron_dynamic_routing_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-dynamic-routing"
neutron_dynamic_routing_git_install_branch: 6288fecb1cf2d5cf22ecbaad97cdfbc1b407ba2d
neutron_dynamic_routing_git_track_branch: stable/2026.2

networking_bgpvpn_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-bgpvpn"
networking_bgpvpn_git_install_branch: fc2b18f2d3f6ea80e8e51aac70a8137583bb55a5
networking_bgpvpn_git_track_branch: stable/2026.2

networking_sfc_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-sfc"
networking_sfc_git_install_branch: 745adb0cf3792d986de174e0486bf68f9120739f
networking_sfc_git_track_branch: stable/2026.2

networking_generic_switch_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-generic-switch"
networking_generic_switch_git_install_branch: 65f05f1ba7b25904cc976a2a7cd0e719b7d2eca4
networking_generic_switch_git_track_branch: stable/2026.2

networking_nsx_git_repo: "{{ openstack_opendev_base_url }}/x/vmware-nsx"
networking_nsx_git_install_branch: 715cb5fc1174b9226f043e49ffd389add44f070a
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: "{{ openstack_opendev_base_url }}/x/vmware-nsxlib"
networking_nsxlib_git_install_branch: 315a42f28e8a9e0e75773dbd8263bc11a72288df
networking_nsxlib_git_track_branch: master

networking_baremetal_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-baremetal"
networking_baremetal_git_install_branch: afaf138edd81ce7c742a9702e9f231748d720d57
networking_baremetal_git_track_branch: stable/2026.2

networking_ovn_bgp_git_repo: "{{ openstack_opendev_base_url }}/openstack/ovn-bgp-agent"
networking_ovn_bgp_git_install_branch: f770768b41dc78de7d0825c0cddb0328b9808e14
networking_ovn_bgp_git_track_branch: stable/2026.2
